repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # Use the latest stable version
    hooks:
      - id: prettier
        args: [--write]
