[project]
name = "unstructured2graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "unstructured[all-docs]>=0.12.6",
    "tqdm>=4.65.0",
]
